version: '3.9'

services:

  db:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: onepieceisreal
      POSTGRES_USER: luffy
      POSTGRES_DB: onepiece
    ports:
      - "5432:5432"