version: '3.9'

services:

  server:
    container_name: server
    environment:
      - DATABASE_URL=postgresql://luffy:onepieceisreal@db:5432/onepiece
    command: ["npm", "run", "dev"]
    volumes:
      - ./server:/app # we need to mount the server directory to the container for hot-reloading
      - /app/node_modules
    depends_on:
      - db

  client:
    container_name: client
    build: ./client
    command: ["npm", "run", "dev"]
    volumes:
      - ./client:/app # we need to mount the client directory to the container for hot-reloading
      - /app/node_modules
