version: '3.9'

services:
  client:
    container_name: client
    build: ./client
    command: ["npm", "run", "dev"]
    volumes:
      - ./client:/app # we need to mount the client directory to the container for hot-reloading
      - /app/node_modules

  db:
    container_name: db
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"